---
title: "coord_map"
output: html_document
---

Projects a portion of the earth, which is approximately spherical, onto a flat 2D plane using any projection defined by the mapproj package and then convert them with ggplotly.

```{r setup, include=FALSE}
library(rvest);library(xml2);library(httr)
library(ggplot2); library(maps);library(mapproj)

knitr::opts_chunk$set(
  class.output  = "bg-light"
)
```

```{r, include=FALSE}
url <- "https://ggplot2.tidyverse.org/reference/coord_map.html"
uastring <- "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36"
session <- html_session(url, user_agent(uastring))
s <- html_text(html_nodes(session, xpath = "//*[@class='input']"))
s <- unlist(strsplit(s, split = '\n', fixed = TRUE))
```

```{r example1, echo=F}
z <- s[1:9]
z_1 <- paste("p <- ", "\n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./coord_map/example1.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example2, echo=F}
z <- s[11:14]
z_1 <- paste("p <- ", "\n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./coord_map/example2.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example3, echo=F}
z <- s[16:19]
z_1 <- paste("p <- ", "\n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./coord_map/example3.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example4, echo=F}
z <- s[21:24]
z_1 <- paste("p <- ", "\n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./coord_map/example4.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example5, echo=F}
z <- s[26:33]
z_1 <- paste("p <- ", "\n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./coord_map/example5.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example6, echo=F}
z <- s[35:38]
z_1 <- paste("p <- ", "\n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./coord_map/example6.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example7, echo=F}
z <- s[40:43]
z_1 <- paste("p <- ", "\n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./coord_map/example7.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example8, echo=F}
z <- s[45:50]
z_1 <- paste("p <- ", "\n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./coord_map/example8.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example9, echo=F}
z <- s[52:54]
z_1 <- paste("p <- ", "\n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./coord_map/example9.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example10, echo=F}
z <- s[56:58]
z_1 <- paste("p <- ", "\n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./coord_map/example10.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example11, echo=F}
z <- s[60:82]
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z)
write(z, "./coord_map/example11.R")
```








