---
title: "geom_map"
output: 
  html_document:
    keep_md: true
    self_contained: true
always_allow_html: true
---

Create polygons from a reference map and then convert them with ggplotly

```{r setup, include=FALSE}
library(rvest);library(xml2);library(httr)
library(ggplot2);library(maps)

knitr::opts_chunk$set(
  class.output  = "bg-light"
)
```

```{r, include=FALSE}
url <- "https://ggplot2.tidyverse.org/reference/geom_map.html"
uastring <- "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36"
session <- html_session(url, user_agent(uastring))
s <- html_text(html_nodes(session, xpath = "//*[@class='input']"))
s <- unlist(strsplit(s, split = '\n', fixed = TRUE))
```

```{r example1, echo=F}
y <- s[6:19]
z <- s[21:23]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_map/example1.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
plotly::api_create(plotly::ggplotly(p), filename = "geom_map_1")
```

```{r example2, echo=F}
y <- s[6:19]
z <- s[24:26]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_map/example2.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
plotly::api_create(plotly::ggplotly(p), filename = "geom_map_2")
```

```{r example3, echo=F}
y <- s[6:19]
z <- s[27:29]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_map/example3.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
plotly::api_create(plotly::ggplotly(p), filename = "geom_map_3")
```

```{r example4, echo=F}
z <- s[32:52]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_map/example4.R")
```

```{r}
plotly::ggplotly(p)
```

```{r echo=F, error=T}
plotly::api_create(plotly::ggplotly(p), filename = "geom_map_4")
```
