---
title: "geom_bin_2d"
output: 
  html_document:
    keep_md: true
    self_contained: true
always_allow_html: true
---

Divides the plane into rectangles, counts the number of cases in each rectangle, and then (by default) maps the number of cases to the rectangle's fill and then convert them with ggplotly.

```{r setup, include=FALSE}
library(rvest);library(xml2);library(httr)
library(ggplot2)

knitr::opts_chunk$set(
  class.output  = "bg-light"
)
source("D:/Personal/Upwork/Contract/rvest - Jack/ggplot_scrap/functions.R")
```

```{r, include=FALSE}
url <- "https://ggplot2.tidyverse.org/reference/geom_bin_2d.html"
uastring <- "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36"
session <- html_session(url, user_agent(uastring))
s <- html_text(html_nodes(session, xpath = "//*[@class='input']"))
s <- unlist(strsplit(s, split = '\n', fixed = TRUE))
```

```{r example1, echo=F}
y <- s[1]
z <- s[2]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_bin_2d/example1.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_bin_2d_1")
```

```{r example2, echo=F}
y <- s[1]
z <- s[6]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_bin_2d/example2.R")
```

```{r}
plotly::ggplotly(p)
```

```{r echo=F}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_bin_2d_2")
```

```{r example3, echo=F}
y <- s[1]
z <- s[7]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_bin_2d/example3.R")
```

```{r}
plotly::ggplotly(p)
```

```{r echo=F}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_bin_2d_3")
```

```{r example4, echo=F}
y <- s[1]
z <- s[10]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_bin_2d/example4.R")
```

```{r}
plotly::ggplotly(p)
```

```{r echo=F}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_bin_2d_4")
```


