---
title: "geom_boxplot"
output: 
  html_document:
    keep_md: true
    self_contained: true
always_allow_html: true
---

Creates boxplot and then convert them with ggplotly.

```{r setup, include=FALSE}
library(rvest);library(xml2);library(httr)
library(ggplot2)

knitr::opts_chunk$set(
  class.output  = "bg-light"
)
source("D:/Personal/Upwork/Contract/rvest - Jack/ggplot_scrap/functions.R")
```

```{r, include=FALSE}
url <- "https://ggplot2.tidyverse.org/reference/geom_boxplot.html"
uastring <- "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36"
session <- html_session(url, user_agent(uastring))
s <- html_text(html_nodes(session, xpath = "//*[@class='input']"))
s <- unlist(strsplit(s, split = '\n', fixed = TRUE))
```

```{r example1, echo=F}
y <- s[1]
z <- s[2]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_boxplot/example1.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_boxplot_1")
```

```{r example2, echo=F}
z <- s[4]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_boxplot/example2.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_boxplot_2")
```

```{r example3, echo=F}
y <- s[1]
z <- s[6]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_boxplot/example3.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_boxplot_3")
```

```{r example4, echo=F}
y <- s[1]
z <- s[7]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_boxplot/example4.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_boxplot_4")
```

```{r example5, echo=F}
y <- s[1]
z <- s[8]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_boxplot/example5.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_boxplot_5")
```

```{r example6, echo=F}
y <- s[1]
z <- s[11]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_boxplot/example6.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_boxplot_6")
```

```{r example7, echo=F}
y <- s[1]
z <- s[13]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_boxplot/example7.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_boxplot_7")
```

```{r example8, echo=F}
y <- s[1]
z <- s[16]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_boxplot/example8.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_boxplot_8")
```

```{r example9, echo=F}
z <- s[20:21]
z_1 <- paste("p <- ", "  \n", paste(z, collapse='\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_boxplot/example9.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_boxplot_9")
```

```{r example10, echo=F}
z <- s[22:23]
z_1 <- paste("p <- ", "  \n", paste(z, collapse='\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_boxplot/example10.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_boxplot_10")
```

```{r example11, echo=F}
z <- s[25:26]
z_1 <- paste("p <- ", "  \n", paste(z, collapse='\n'))
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_boxplot/example11.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_boxplot_11")
```

```{r example12, echo=F}
y <- s[31]
z_0 <- s[32:39]
z <- s[40:44]
z_1 <- paste("p <- ", "  \n", paste(z, collapse='\n'))
p <- eval(parse(text = c(s[31],z_0,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(s[31],z_0,z_1))
write(c(s[31],z_0,z_1), "./geom_boxplot/example12.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_boxplot_12")
```