---
title: "geom_rug"
output: html_document
---

Supplement a 2d display with the two 1d marginal distributions and then convert them with ggplotly

```{r setup, include=FALSE}
library(rvest);library(xml2);library(httr)
library(ggplot2)

knitr::opts_chunk$set(
  class.output  = "bg-light"
)
```

```{r, include=FALSE}
url <- "https://ggplot2.tidyverse.org/reference/geom_rug.html"
uastring <- "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36"
session <- html_session(url, user_agent(uastring))
s <- html_text(html_nodes(session, xpath = "//*[@class='input']"))
s <- unlist(strsplit(s, split = '\n', fixed = TRUE))
```

```{r example1, echo=F}
z <- s[1:2]
z_1 <- paste(z, collapse = '\n')
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_rug/example1.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example2, echo=F}
z_0 <- s[1:2]
z <- s[4]
z_00 <- paste(z_0, collapse = '\n')
z_1 <- paste("p <-", z)
p <- eval(parse(text = c(z_0,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(z_00,z_1))
write(c(z_00,z_1), "./geom_rug/example2.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example3, echo=F}
z_0 <- s[1:2]
z <- s[5]
z_00 <- paste(z_0, collapse = '\n')
z_1 <- paste("p <-", z)
p <- eval(parse(text = c(z_0,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(z_00,z_1))
write(c(z_00,z_1), "./geom_rug/example3.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example4, echo=F}
z_0 <- s[1:2]
z <- s[6]
z_00 <- paste(z_0, collapse = '\n')
z_1 <- paste("p <-", z)
p <- eval(parse(text = c(z_0,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(z_00,z_1))
write(c(z_00,z_1), "./geom_rug/example4.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example5, echo=F}
z <- s[9:11]
z_1 <- paste("p <-", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_rug/example5.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example6, echo=F}
z <- s[13:15]
z_1 <- paste("p <-", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_rug/example6.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example7, echo=F}
z_0 <- s[1:2]
z <- s[19:21]
z_00 <- paste(z_0, collapse = '\n')
z_1 <- paste("p <-", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = c(z_0,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(z_0,z_1))
write(c(z_0,z_1), "./geom_rug/example7.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example8, echo=F}
z_0 <- s[1:2]
z <- s[24:27]
z_00 <- paste(z_0, collapse = '\n')
z_1 <- paste("p <-", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = c(z_0,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(z_0,z_1))
write(c(z_0,z_1), "./geom_rug/example8.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example9, echo=F}
z_0 <- s[1:2]
z <- s[31:33]
z_00 <- paste(z_0, collapse = '\n')
z_1 <- paste("p <-", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = c(z_0,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(z_0,z_1))
write(c(z_0,z_1), "./geom_rug/example7.R")
```

```{r}
plotly::ggplotly(p)
```

