---
title: "geom_histogram"
output: 
  html_document:
    keep_md: true
    self_contained: true
always_allow_html: true
---

Visualise the distribution of a single continuous variable by dividing the x axis into bins and counting the number of observations in each bin and then convert them with ggplotly

```{r setup, include=FALSE}
library(rvest);library(xml2);library(httr)
library(ggplot2);library(ggplot2movies)

knitr::opts_chunk$set(
  class.output  = "bg-light"
)
source("D:/Personal/Upwork/Contract/rvest - Jack/ggplot_scrap/functions.R")
```

```{r, include=FALSE}
url <- "https://ggplot2.tidyverse.org/reference/geom_histogram.html"
uastring <- "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36"
session <- html_session(url, user_agent(uastring))
s <- html_text(html_nodes(session, xpath = "//*[@class='input']"))
s <- unlist(strsplit(s, split = '\n', fixed = TRUE))
```

```{r example1, echo=F}
z <- s[1:2]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_histogram/example1.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_histogram_1")
```

```{r example2, echo=F}
z <- s[3:4]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_histogram/example2.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_histogram_2")
```

```{r example3, echo=F}
z <- s[5:6]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_histogram/example3.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_histogram_3")
```

```{r example4, echo=F}
z <- s[8:9]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_histogram/example4.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_histogram_4")
```

```{r example5, echo=F}
z <- s[13:15]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_histogram/example5.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_histogram_5")
```

```{r example6, echo=F}
z <- s[19:20]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_histogram/example6.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_histogram_6")
```

```{r example7, echo=F}
z <- s[21:22]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_histogram/example7.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_histogram_7")
```

```{r example8, echo=F}
z <- s[26:27]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_histogram/example8.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_histogram_8")
```

```{r example9, echo=F}
z <- s[c(29,34:35,39:41,45:50,59:61,63:65,69:73)]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_histogram/example9.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_histogram_9")
```

```{r example10, echo=F}
z <- s[78:80]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_histogram/example10.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_histogram_10")
```