---
title: "geom_dotplot"
output: 
  html_document:
    keep_md: true
    self_contained: true
always_allow_html: true
---

Creates dotplot and then convert them with ggplotly.

```{r setup, include=FALSE}
library(rvest);library(xml2);library(httr)
library(ggplot2)

knitr::opts_chunk$set(
  class.output  = "bg-light"
)
source("D:/Personal/Upwork/Contract/rvest - Jack/ggplot_scrap/functions.R")
```

```{r, include=FALSE}
url <- "https://ggplot2.tidyverse.org/reference/geom_dotplot.html"
uastring <- "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36"
session <- html_session(url, user_agent(uastring))
s <- html_text(html_nodes(session, xpath = "//*[@class='input']"))
s <- unlist(strsplit(s, split = '\n', fixed = TRUE))
```

```{r example1, echo=F}
z <- s[1:2]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_dotplot/example1.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_dotplot_1")
```

```{r example2, echo=F}
z <- s[4:5]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_dotplot/example2.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_dotplot_2")
```

```{r example3, echo=F}
z <- s[8:9]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_dotplot/example3.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_dotplot_3")
```

```{r example4, echo=F}
z <- s[12:13]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_dotplot/example4.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_dotplot_4")
```

```{r example5, echo=F}
z <- s[15:16]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_dotplot/example5.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_dotplot_5")
```

```{r example6, echo=F}
z <- s[19:20]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_dotplot/example6.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_dotplot_6")
```

```{r example7, echo=F}
z <- s[23:24]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_dotplot/example7.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_dotplot_7")
```

```{r example8, echo=F}
z <- s[27:28]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_dotplot/example8.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_dotplot_8")
```

```{r example9, echo=F}
z <- s[31:32]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_dotplot/example9.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_dotplot_9")
```

```{r example10, echo=F}
z <- s[36:37]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_dotplot/example10.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_dotplot_10")
```

```{r example11, echo=F}
z <- s[39:40]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_dotplot/example11.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_dotplot_11")
```

```{r example12, echo=F}
z <- s[42:43]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_dotplot/example12.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_dotplot_12")
```

```{r example13, echo=F}
z <- s[45:46]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_dotplot/example13.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_dotplot_13")
```

```{r example14, echo=F}
z <- s[49:50]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_dotplot/example14.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_dotplot_14")
```

```{r example15, echo=F}
z <- s[53:54]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_dotplot/example15.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_dotplot_15")
```

```{r example16, echo=F}
z <- s[56:57]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_dotplot/example16.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_dotplot_16")
```

```{r example17, echo=F}
z <- s[59:60]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_dotplot/example17.R")
```

```{r}
plotly::ggplotly(p)
```

```{r include=F, error=T}
# plotly::api_create(plotly::ggplotly(p), filename = "geom_dotplot_17")
```
