---
title: "geom_tile"
output: 
  html_document:
    keep_md: true
    self_contained: true
always_allow_html: true
---

Creates rectangles and then convert them with ggplotly.

```{r setup, include=FALSE}
library(rvest);library(xml2);library(httr)
library(ggplot2)

knitr::opts_chunk$set(
  class.output  = "bg-light"
)
source("D:/Personal/Upwork/Contract/rvest - Jack/ggplot_scrap/functions.R")
```

```{r, include=FALSE}
url <- "https://ggplot2.tidyverse.org/reference/geom_tile.html"
uastring <- "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36"
session <- html_session(url, user_agent(uastring))
s <- html_text(html_nodes(session, xpath = "//*[@class='input']"))
s <- unlist(strsplit(s, split = '\n', fixed = TRUE))
```

```{r example1, echo=F}
z <- s[4:5]
z_1 <- paste("p <-", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_tile/example1.R")
```

```{r}
plotly::ggplotly(p)
```

```{r echo=F, error=T}
plotly::api_create(plotly::ggplotly(p), filename = "geom_tile_a")
```

```{r example2, echo=F}
z <- s[8:9]
z_1 <- paste("p <-", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./geom_tile/example2.R")
```

```{r}
plotly::ggplotly(p)
```

```{r echo=F, error=T}
plotly::api_create(plotly::ggplotly(p), filename = "geom_tile_b")
```

```{r example3, echo=F}
y <- s[12:17]
z <- s[18:19]
z_1 <- paste("p <-", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_tile/example3.R")
```

```{r}
plotly::ggplotly(p)
```

```{r echo=F, error=T}
plotly::api_create(plotly::ggplotly(p), filename = "geom_tile_c")
```

```{r example4, echo=F}
y <- s[12:17]
z <- s[20:21]
z_1 <- paste("p <-", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_tile/example4.R")
```

```{r}
plotly::ggplotly(p)
```

```{r echo=F, error=T}
plotly::api_create(plotly::ggplotly(p), filename = "geom_tile_d")
```

```{r example5, echo=F}
y <- s[12:17]
z <- s[22:23]
z_1 <- paste("p <-", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_tile/example5.R")
```

```{r}
plotly::ggplotly(p)
```

```{r echo=F, error=T}
plotly::api_create(plotly::ggplotly(p), filename = "geom_tile_e")
```

```{r example6, echo=F}
y <- s[27:28]
z <- s[30:31]
z_1 <- paste("p <-", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_tile/example6.R")
```

```{r}
plotly::ggplotly(p)
```

```{r echo=F, error=T}
plotly::api_create(plotly::ggplotly(p), filename = "geom_tile_f")
```

```{r example7, echo=F}
y <- s[27:28]
z <- s[33:34]
z_1 <- paste("p <-", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_tile/example7.R")
```

```{r}
plotly::ggplotly(p)
```

```{r echo=F, error=T}
plotly::api_create(plotly::ggplotly(p), filename = "geom_tile_g")
```

```{r example8, echo=F}
y <- s[37]
z <- s[38]
z_1 <- paste("p <-", z)
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_tile/example8.R")
```

```{r}
plotly::ggplotly(p)
```

```{r echo=F, error=T}
plotly::api_create(plotly::ggplotly(p), filename = "geom_tile_h")
```

```{r example9, echo=F}
y <- s[37]
z <- s[39]
z_1 <- paste("p <-", z)
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_tile/example9.R")
```

```{r}
plotly::ggplotly(p)
```

```{r echo=F, error=T}
plotly::api_create(plotly::ggplotly(p), filename = "geom_tile_i")
```

```{r example10, echo=F}
y <- s[37]
z <- s[40]
z_1 <- paste("p <-", z)
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_tile/example10.R")
```

```{r}
plotly::ggplotly(p)
```

```{r echo=F, error=T}
plotly::api_create(plotly::ggplotly(p), filename = "geom_tile_j")
```

```{r example11, echo=F}
y <- s[37]
z <- s[42:47]
z_1 <- paste("p <-", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_tile/example11.R")
```

```{r}
plotly::ggplotly(p)
```

```{r echo=F, error=T}
plotly::api_create(plotly::ggplotly(p), filename = "geom_tile_k")
```

```{r example12, echo=F}
y <- s[37]
z <- s[48:53]
z_1 <- paste("p <-", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = c(y,z)))
```

```{r, echo=F, comment=NA}
writeLines(c(y,z_1))
write(c(y,z_1), "./geom_tile/example12.R")
```

```{r}
plotly::ggplotly(p)
```

```{r echo=F, error=T}
plotly::api_create(plotly::ggplotly(p), filename = "geom_tile_l")
```