---
title: "after_stat"
output: html_document
---

Map from stat transformed data, flag evaluation of mapping for after data has been scaled, map the same aesthetic multiple times but remap it for the geom, and then convert it into ggplotly

```{r setup, include=FALSE}
library(rvest);library(xml2);library(httr)
library(ggplot2)

knitr::opts_chunk$set(
  class.output  = "bg-light"
)
```

```{r, include=FALSE}
url <- "https://ggplot2.tidyverse.org/reference/aes_eval.html"
uastring <- "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36"
session <- html_session(url, user_agent(uastring))
s <- html_text(html_nodes(session, xpath = "//*[@class='input']"))
s <- unlist(strsplit(s, split = '\n', fixed = TRUE))
```

```{r example1, echo=F}
z <- s[2:3]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./after_stat/example1.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example2, echo=F}
z <- s[6:7]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./after_stat/example2.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example3, echo=F}
z <- s[10:11]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./after_stat/example3.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example4, echo=F}
z <- s[14:15]
z_1 <- paste("p <- ", "  \n", paste(z, collapse = '\n'))
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./after_stat/example4.R")
```

```{r}
plotly::ggplotly(p)
```