---
title: "theme_get"
output: html_document
---

Give complete themes which control all non-data display and then convert them with ggplotly.

```{r setup, include=FALSE}
library(rvest);library(xml2);library(httr)
library(ggplot2)

knitr::opts_chunk$set(
  class.output  = "bg-light"
)
```

```{r, include=FALSE}
url <- "https://ggplot2.tidyverse.org/reference/theme_get.html"
uastring <- "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36"
session <- html_session(url, user_agent(uastring))
s <- html_text(html_nodes(session, xpath = "//*[@class='input']"))
s <- unlist(strsplit(s, split = '\n', fixed = TRUE))
```

```{r example1, echo=F}
z <- s[1:3]
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z)
write(z, "./theme_get/example1.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example2, echo=F}
z <- s[c(1:2,12,13)]
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z)
write(z, "./theme_get/example2.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example3, echo=F}
z <- s[c(1:2,12,15:17)]
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z)
write(z, "./theme_get/example3.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example4, echo=F}
z <- s[c(1:2,12,19:21)]
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z)
write(z, "./theme_get/example4.R")
```

```{r}
plotly::ggplotly(p)
```

```{r example5, echo=F}
z <- s[c(1:2,12,23:24)]
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z)
write(z, "./theme_get/example5.R")
```

```{r}
plotly::ggplotly(p)
```

