---
title: "aes"
output: 
  html_document:
    keep_md: true
    self_contained: true
always_allow_html: true
---

Construct aesthetic mappings and then convert them with ggplotly

```{r setup, include=FALSE}
library(rvest);library(xml2);library(httr)
library(ggplot2)

knitr::opts_chunk$set(
  class.output  = "bg-light"
)

source("D:/Personal/Upwork/Contract/rvest - Jack/ggplot_scrap/functions.R")
```

```{r, include=FALSE}
url <- "https://ggplot2.tidyverse.org/reference/aes.html"
uastring <- "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36"
session <- html_session(url, user_agent(uastring))
s <- html_text(html_nodes(session, xpath = "//*[@class='input']"))
s <- unlist(strsplit(s, split = '\n', fixed = TRUE))
```

```{r example1, echo=F}
z <- s[18]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./aes/example1.R")
```

```{r}
plotly::ggplotly(p)
```

```{r}
# plotly::api_create(plotly::ggplotly(p), filename = "aes_1")
```


```{r example2, echo=F}
z <- s[19]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./aes/example2.R")
```

```{r}
plotly::ggplotly(p)
```

```{r}
# plotly::api_create(plotly::ggplotly(p), filename = "aes_2")
```

```{r example3, echo=F}
z_0 <- s[25:27]
z <- s[28]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = c(z_0, z)))
```

```{r, echo=F, comment=NA}
writeLines(c(z_0, z_1))
write(c(z_0, z_1), "./aes/example3.R")
```

```{r}
plotly::ggplotly(p)
```

```{r}
# plotly::api_create(plotly::ggplotly(p), filename = "aes_3")
```

```{r example4, echo=F}
z_0 <- s[32:37]
z <- s[38]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = c(z_0, z)))
```

```{r, echo=F, comment=NA}
writeLines(c(z_0, z_1))
write(c(z_0, z_1), "./aes/example4.R")
```

```{r}
plotly::ggplotly(p)
```

```{r}
# plotly::api_create(plotly::ggplotly(p), filename = "aes_4")
```

```{r example5, echo=F}
z_0 <- s[42]
z <- s[43]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = c(z_0, z)))
```

```{r, echo=F, comment=NA}
writeLines(c(z_0, z_1))
write(c(z_0, z_1), "./aes/example5.R")
```

```{r}
plotly::ggplotly(p)
```

```{r}
# plotly::api_create(plotly::ggplotly(p), filename = "aes_5")
```

