---
title: "Quick plot"
output: 
  html_document:
    keep_md: true
    self_contained: true
always_allow_html: true
---

Convenient wrapper for creating a number of different types of plots using a consistent calling scheme and then convert them with ggplotly

```{r setup, include=FALSE}
library(rvest);library(xml2);library(httr)
library(ggplot2)

knitr::opts_chunk$set(
  class.output  = "bg-light"
)

source("D:/Personal/Upwork/Contract/rvest - Jack/ggplot_scrap/functions.R")
```

```{r, include=FALSE}
url <- "https://ggplot2.tidyverse.org/reference/qplot.html"
uastring <- "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36"
session <- html_session(url, user_agent(uastring))
s <- html_text(html_nodes(session, xpath = "//*[@class='input']"))
s <- unlist(strsplit(s, split = '\n', fixed = TRUE))
```

```{r example1, echo=F}
z <- s[2]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./qplot/example1.R")
```

```{r}
plotly::ggplotly(p)
```

```{r}
# plotly::api_create(plotly::ggplotly(p), filename = "qplot_1")
```


```{r example2, echo=F}
z <- s[3]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./qplot/example2.R")
```

```{r}
plotly::ggplotly(p)
```

```{r}
# plotly::api_create(plotly::ggplotly(p), filename = "qplot_2")
```


```{r example3, echo=F}
z <- s[4]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./qplot/example3.R")
```

```{r}
plotly::ggplotly(p)
```

```{r}
# plotly::api_create(plotly::ggplotly(p), filename = "qplot_3")
```

```{r example4, echo=F}
z <- s[5]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./qplot/example4.R")
```

```{r}
plotly::ggplotly(p)
```

```{r}
# plotly::api_create(plotly::ggplotly(p), filename = "qplot_4")
```

```{r example5, echo=F}
z <- s[8]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./qplot/example5.R")
```

```{r}
plotly::ggplotly(p)
```

```{r}
# plotly::api_create(plotly::ggplotly(p), filename = "qplot_5")
```

```{r example6, echo=F}
z <- s[9]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./qplot/example6.R")
```

```{r}
plotly::ggplotly(p)
```

```{r}
# plotly::api_create(plotly::ggplotly(p), filename = "qplot_6")
```

```{r example7, echo=F}
z_0 <- s[10]
z <- s[11]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = c(z_0,z_1)))
```

```{r, echo=F, comment=NA}
writeLines(c(z_0,z_1))
write(c(z_0,z_1), "./qplot/example7.R")
```

```{r}
plotly::ggplotly(p)
```

```{r}
# plotly::api_create(plotly::ggplotly(p), filename = "qplot_7")
```

```{r example8, echo=F}
z_0 <- s[13:17]
z <- s[18]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = c(z_0,z_1)))
```

```{r, echo=F, comment=NA}
writeLines(c(z_0,z_1))
write(c(z_0,z_1), "./qplot/example8.R")
```

```{r}
plotly::ggplotly(p)
```

```{r}
# plotly::api_create(plotly::ggplotly(p), filename = "qplot_8")
```

```{r example9, echo=F}
z <- s[21]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./qplot/example9.R")
```

```{r}
plotly::ggplotly(p)
```

```{r}
# plotly::api_create(plotly::ggplotly(p), filename = "qplot_9")
```

```{r example10, echo=F}
z <- s[25]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./qplot/example10.R")
```

```{r}
plotly::ggplotly(p)
```

```{r}
# plotly::api_create(plotly::ggplotly(p), filename = "qplot_10")
```

```{r example11, echo=F}
z <- s[27]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./qplot/example11.R")
```

```{r}
plotly::ggplotly(p)
```

```{r}
# plotly::api_create(plotly::ggplotly(p), filename = "qplot_11")
```

```{r example12, echo=F}
z <- s[29]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./qplot/example12.R")
```

```{r}
plotly::ggplotly(p)
```

```{r}
# plotly::api_create(plotly::ggplotly(p), filename = "qplot_12")
```

```{r example13, echo=F}
z <- s[32]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./qplot/example13.R")
```

```{r}
plotly::ggplotly(p)
```

```{r}
# plotly::api_create(plotly::ggplotly(p), filename = "qplot_13")
```

```{r example14, echo=F}
z <- s[33]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./qplot/example14.R")
```

```{r}
plotly::ggplotly(p)
```

```{r}
# plotly::api_create(plotly::ggplotly(p), filename = "qplot_14")
```

```{r example15, echo=F}
z <- s[34]
z_1 <- paste("p <- ", z)
p <- eval(parse(text = z))
```

```{r, echo=F, comment=NA}
writeLines(z_1)
write(z_1, "./qplot/example15.R")
```

```{r}
plotly::ggplotly(p)
```

```{r}
# plotly::api_create(plotly::ggplotly(p), filename = "qplot_15")
```